
- name: Adds NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: Updates apt-cache
  apt: update_cache=yes

- name: Install NGINX
  apt:
    pkg: nginx
    state: latest

- name: Starting NGINX
  service:
    name: nginx
    state: started

- name: Create default nginx directories
  file:
    path: '/etc/nginx/sites-available'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify:
    - Restart nginx

- name: Setup nginx cluster configuration
  template:
    src: 'nginx.j2'
    dest: '/etc/nginx/sites-available/default'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Restart nginx 

- name: Setup nginx configuration
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Restart nginx

- name: Change privilege to vagrant user
  lineinfile: "dest=/etc/sudoers line='vagrant ALL=(ALL) NOPASSWD: ALL'"
  #lineinfile: dest=/etc/sudoers line="vagrant ALL=(ALL) NOPASSWD{{':'}} ALL" 
